

train_dataset:
  type: Dataset
  dataset_root: data/Crack_seg_lys
  train_path: data/Crack_seg_lys/train.txt
  num_classes: 2
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [400, 400]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/Crack_seg_lys
  val_path: data/Crack_seg_lys/val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize


batch_size: 16
iters: 100000


model:
  type: DDRNet_23
  enable_auxiliary_loss: False
  # pretrained: https://bj.bcebos.com/paddleseg/dygraph/cityscapes/ddrnet23_cityscapes_1024x1024_120k/pretrain/model.pdparams


loss:
  types:
    - type: OhemCrossEntropyLoss
  coef: [1]


optimizer:
  type: sgd
  weight_decay: 0.0005


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9
