

train_dataset:
  type: Dataset
  dataset_root: data/Crack_seg_lys
  train_path: data/Crack_seg_lys/train.txt
  num_classes: 2
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [400, 400]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/Crack_seg_lys
  val_path: data/Crack_seg_lys/val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize


batch_size: 16
iters: 100000


model:
  type: DeepLabV3P
  backbone:
    type: ResNet18_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    # pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 2
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null


loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]


optimizer:
  type: sgd
  weight_decay: 0.0005


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9
