batch_size: 32
iters: 100000

train_dataset:
  type: Dataset
  dataset_root: data/crackseg9k
  train_path: data/crackseg9k/train.txt
  num_classes: 2
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [400, 400]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/crackseg9k
  val_path: data/crackseg9k/val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize


model:
  type: HrSegNetB32


optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 0.0005
  

loss:
  types:
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
  coef: [1, 0.5, 0.5]


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9
  warmup_iters: 2000
  warmup_start_lr: 1.0e-5



  
