

train_dataset:
  type: Dataset
  dataset_root: data/crackseg9k
  train_path: data/crackseg9k/train.txt
  num_classes: 2
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [400, 400]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/crackseg9k
  val_path: data/crackseg9k/val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize


batch_size: 16
iters: 100000

model:
  type: PSPNet
  num_classes: 2
  backbone:
    type: ResNet18_vd
    output_stride: 8
    # pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  enable_auxiliary_loss: True
  align_corners: False
  pretrained: null


optimizer:
  type: sgd
  weight_decay: 0.0005

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  power: 0.9
  end_lr: 1.0e-5
